#!/usr/bin/env python3
"""
NQB — Nasdaq-100 Futures  |  Dashboard
Run: python3 app.py  →  http://127.0.0.1:8050
"""

import sys, os
sys.path.insert(0, os.path.dirname(__file__))

import json
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import dash
from dash import dcc, html, Input, Output, State, dash_table, callback_context
import dash_bootstrap_components as dbc

import config as cfg
import data as datamod
import indicators
import signals as sig_engine
import liquidity as liq
import sessions as sess_mod
import news as news_mod
import alerts as alert_mod
import journal as journal_mod
import database as db_mod
import analytics as ana_mod
import learning as learn_mod
import ml_model
import paper_trading as pt_mod
import tracker as trk_mod
import market_context as mc_mod
import filters as flt_mod

# ── Palette ───────────────────────────────────────────────────────────────────
BG     = "#0a0a0f"
PANEL  = "#111118"
BORDER = "#1e1e2e"
MUTED  = "#4a4a6a"
TEXT   = "#e2e2f0"
DIM    = "#6b6b8a"
GREEN  = "#26a65b"
RED    = "#e84040"
GOLD   = "#c8a84b"
BLUE   = "#4a9eff"
PURPLE = "#9b59b6"

DISCLAIMER_TEXT = (
    "⚠️  DISCLAIMER: NQB is an educational/research tool only — NOT financial advice. "
    "Signals are generated by technical indicators and have not been validated as "
    "statistically predictive of future price movements. Always backtest thoroughly, "
    "paper-trade, and consult a licensed financial advisor before risking real capital. "
    "Futures trading involves substantial risk of loss and is not suitable for all investors."
)

app = dash.Dash(__name__, external_stylesheets=[dbc.themes.DARKLY], title="NQB")
app.config.suppress_callback_exceptions = True

TF_LABELS = {"scalp": "5m", "swing": "1H", "trend": "1D"}

_tab_style       = {"backgroundColor": PANEL,  "color": DIM,  "border": f"1px solid {BORDER}", "borderRadius": "4px 4px 0 0"}
_tab_active      = {"backgroundColor": BORDER, "color": TEXT, "border": f"1px solid {BORDER}", "borderRadius": "4px 4px 0 0"}
_label_style     = {"color": DIM,  "fontSize": "11px", "letterSpacing": "0.06em", "marginBottom": "4px"}
_value_style     = {"color": TEXT, "fontSize": "22px", "fontWeight": "600"}


# ── Shared components ─────────────────────────────────────────────────────────

def _pill(text, color, bg, font_size="13px"):
    return html.Div(text, style={
        "backgroundColor": bg, "color": color,
        "border": f"1px solid {color}",
        "borderRadius": "6px", "padding": "4px 14px",
        "fontSize": font_size, "fontWeight": "700",
        "letterSpacing": "0.05em", "display": "inline-block",
    })


def _stat_card(label, value, color=TEXT):
    return html.Div(style={
        "backgroundColor": PANEL, "border": f"1px solid {BORDER}",
        "borderRadius": "8px", "padding": "14px 18px", "flex": "1",
        "minWidth": "110px", "textAlign": "center",
    }, children=[
        html.Div(label, style=_label_style),
        html.Div(value, style={**_value_style, "color": color}),
    ])


# ── Disclaimer footer ─────────────────────────────────────────────────────────

_disclaimer_footer = html.Div(
    DISCLAIMER_TEXT,
    style={
        "backgroundColor": "#1a0a0a", "border": f"1px solid {RED}",
        "borderRadius": "6px", "padding": "10px 16px",
        "color": "#c07070", "fontSize": "11px", "lineHeight": "1.6",
        "marginTop": "20px",
    },
)


# ── Dashboard tab layout ──────────────────────────────────────────────────────

def _dashboard_layout():
    return html.Div([
        # Top bar
        html.Div(style={
            "display": "flex", "alignItems": "center",
            "justifyContent": "space-between", "marginBottom": "12px",
        }, children=[
            html.Div(style={"display": "flex", "alignItems": "baseline", "gap": "14px"}, children=[
                html.Span("NQ Futures", style={"color": DIM, "fontSize": "12px", "letterSpacing": "0.08em"}),
                html.Span(id="price-display", style={"color": TEXT, "fontSize": "28px", "fontWeight": "600"}),
                html.Span(id="change-display", style={"fontSize": "13px"}),
            ]),
            html.Div(id="signal-display", style={"textAlign": "center"}),
            html.Div(style={"display": "flex", "gap": "4px"}, children=[
                html.Button(label, id=f"btn-{key}", n_clicks=0, style={
                    "background": PANEL, "color": DIM, "border": f"1px solid {BORDER}",
                    "borderRadius": "6px", "padding": "5px 13px", "fontSize": "13px",
                    "cursor": "pointer", "fontWeight": "500",
                }) for key, label in TF_LABELS.items()
            ]),
        ]),

        # Info row: MTF badge, session badge, grade badge
        html.Div(id="info-row", style={"display": "flex", "gap": "8px", "marginBottom": "10px",
                                        "flexWrap": "wrap", "alignItems": "center"}),

        # News warning
        html.Div(id="news-warning", style={"marginBottom": "10px"}),

        # Trade strip
        html.Div(id="trade-strip", style={"marginBottom": "12px", "minHeight": "36px"}),

        # Main chart
        dcc.Graph(id="main-chart",
                  style={"height": "calc(100vh - 280px)", "minHeight": "500px"},
                  config={"displayModeBar": False, "scrollZoom": True,
                          "doubleClick": "reset", "showTips": False}),

        dcc.Store(id="active-tf", data="swing"),
        dcc.Store(id="last-alert-key", data=""),
        dcc.Interval(id="refresh-timer", interval=60_000, n_intervals=0),
    ])


# ── Backtest tab layout ───────────────────────────────────────────────────────

def _backtest_layout():
    return html.Div(style={"padding": "4px 0"}, children=[
        html.Div(style={"display": "flex", "gap": "12px", "alignItems": "center", "marginBottom": "18px"}, children=[
            html.Span("Timeframe:", style={"color": DIM, "fontSize": "13px"}),
            dcc.Dropdown(
                id="bt-tf-select",
                options=[{"label": f"{v}  ({k})", "value": k} for k, v in TF_LABELS.items()],
                value="swing",
                clearable=False,
                style={"width": "180px", "backgroundColor": PANEL, "color": TEXT,
                       "border": f"1px solid {BORDER}"},
            ),
            html.Button("▶  Run Backtest", id="bt-run-btn", n_clicks=0, style={
                "background": BLUE, "color": "#000", "border": "none",
                "borderRadius": "6px", "padding": "8px 20px",
                "fontSize": "13px", "fontWeight": "700", "cursor": "pointer",
            }),
            html.Span(
                "Results are approximate — no slippage, commissions, or fill delays modeled.",
                style={"color": DIM, "fontSize": "11px"},
            ),
        ]),

        dcc.Loading(id="bt-loading", type="circle", color=BLUE, children=[
            html.Div(id="bt-stats-row", style={"display": "flex", "gap": "10px",
                                                "flexWrap": "wrap", "marginBottom": "18px"}),
            html.Div(id="bt-by-signal", style={"marginBottom": "18px"}),
            dcc.Graph(id="bt-equity-chart",
                      style={"height": "260px", "marginBottom": "18px"},
                      config={"displayModeBar": False}),
            html.Div(id="bt-trade-table"),
        ]),
    ])


# ── Risk calculator tab layout ────────────────────────────────────────────────

def _risk_layout():
    def _input(label, id_, value, step=1, min_=0, suffix=""):
        return html.Div(style={"marginBottom": "16px"}, children=[
            html.Label(label, style={**_label_style, "display": "block"}),
            html.Div(style={"display": "flex", "alignItems": "center", "gap": "8px"}, children=[
                dcc.Input(
                    id=id_, type="number", value=value, step=step, min=min_,
                    style={
                        "backgroundColor": PANEL, "color": TEXT,
                        "border": f"1px solid {BORDER}", "borderRadius": "6px",
                        "padding": "8px 12px", "width": "160px", "fontSize": "15px",
                    },
                ),
                html.Span(suffix, style={"color": DIM, "fontSize": "13px"}),
            ]),
        ])

    return html.Div(style={"maxWidth": "760px", "padding": "4px 0"}, children=[
        html.H6("Position Size Calculator", style={"color": TEXT, "marginBottom": "18px"}),

        html.Div(style={"display": "grid", "gridTemplateColumns": "1fr 1fr", "gap": "0 32px"}, children=[
            html.Div([
                _input("Account Size",        "rc-account",   cfg.DEFAULT_ACCOUNT_SIZE, step=1000, suffix="USD"),
                _input("Risk Per Trade",       "rc-risk-pct",  cfg.DEFAULT_RISK_PCT,     step=0.1,  suffix="%"),
                _input("Hard Max Loss",        "rc-max-loss",  cfg.DEFAULT_MAX_LOSS,     step=50,   suffix="USD"),
                _input("Entry Price (pts)",    "rc-entry",     0,                        step=0.25, suffix="pts"),
                _input("Stop Price (pts)",     "rc-stop",      0,                        step=0.25, suffix="pts"),
            ]),
            html.Div([
                html.Div(style={"marginBottom": "16px"}, children=[
                    html.Label("Contract Type", style={**_label_style, "display": "block"}),
                    dcc.RadioItems(
                        id="rc-contract-type",
                        options=[
                            {"label": "  NQ  ($20/pt)", "value": "NQ"},
                            {"label": "  MNQ  ($2/pt)", "value": "MNQ"},
                        ],
                        value="MNQ",
                        inline=True,
                        style={"color": TEXT, "fontSize": "14px", "gap": "24px"},
                    ),
                ]),
                html.Div(id="rc-results", style={"marginTop": "8px"}),
                html.Div(style={
                    "backgroundColor": "#1a120a", "border": f"1px solid {GOLD}",
                    "borderRadius": "6px", "padding": "10px 14px", "marginTop": "20px",
                    "color": "#b89040", "fontSize": "11px", "lineHeight": "1.7",
                }, children=[
                    html.Strong("NQ specs: ", style={"color": GOLD}),
                    "Tick = 0.25 pts = $5  |  1 full pt = $20  |  Initial margin ~$18,000",
                    html.Br(),
                    html.Strong("MNQ specs: ", style={"color": GOLD}),
                    "Tick = 0.25 pts = $0.50  |  1 full pt = $2  |  Initial margin ~$1,800",
                ]),
            ]),
        ]),
    ])


# ── Trade journal tab layout ──────────────────────────────────────────────────

def _journal_layout():
    return html.Div(style={"padding": "4px 0"}, children=[
        html.Div(style={"display": "flex", "gap": "10px", "alignItems": "center",
                        "marginBottom": "14px"}, children=[
            html.H6("Trade Journal", style={"color": TEXT, "margin": "0"}),
            html.Button("↺  Refresh", id="jrn-refresh-btn", n_clicks=0, style={
                "background": PANEL, "color": DIM, "border": f"1px solid {BORDER}",
                "borderRadius": "6px", "padding": "5px 14px",
                "fontSize": "12px", "cursor": "pointer",
            }),
            html.Button("⬇  Export CSV", id="jrn-export-btn", n_clicks=0, style={
                "background": PANEL, "color": GREEN, "border": f"1px solid {GREEN}",
                "borderRadius": "6px", "padding": "5px 14px",
                "fontSize": "12px", "cursor": "pointer",
            }),
            dcc.Download(id="jrn-download"),
            html.Span(
                "Edit 'outcome' (WIN / LOSS / BE) and 'pnl_pts' directly in the table below.",
                style={"color": DIM, "fontSize": "11px"},
            ),
        ]),
        html.Div(id="jrn-table-container"),
        dcc.Store(id="jrn-store"),
    ])


# ── Analytics tab layout ─────────────────────────────────────────────────────

def _analytics_layout():
    def _btn(label, id_, color=BLUE):
        return html.Button(label, id=id_, n_clicks=0, style={
            "background": color, "color": "#000" if color == BLUE else TEXT,
            "border": f"1px solid {color}", "borderRadius": "6px",
            "padding": "6px 16px", "fontSize": "12px",
            "fontWeight": "600", "cursor": "pointer", "marginRight": "8px",
        })

    return html.Div(style={"padding": "4px 0"}, children=[
        html.Div(style={"display": "flex", "alignItems": "center",
                        "gap": "8px", "marginBottom": "16px", "flexWrap": "wrap"}, children=[
            _btn("↺  Refresh Analytics",  "ana-refresh-btn"),
            _btn("⚙  Run Weight Update",  "ana-weight-btn", PURPLE),
            _btn("🤖  Train ML Model",    "ana-ml-train-btn", GOLD),
            html.Span(id="ana-status", style={"color": DIM, "fontSize": "12px"}),
        ]),

        dcc.Loading(type="circle", color=BLUE, children=[
            # Summary stats
            html.Div(id="ana-summary-row",
                     style={"display": "flex", "gap": "10px",
                             "flexWrap": "wrap", "marginBottom": "18px"}),

            # Breakdown tables row
            html.Div(style={"display": "grid",
                             "gridTemplateColumns": "1fr 1fr 1fr 1fr",
                             "gap": "16px", "marginBottom": "18px"}, children=[
                html.Div([html.Div("By Timeframe",  style={**_label_style, "marginBottom": "6px"}),
                          html.Div(id="ana-tf-table")]),
                html.Div([html.Div("By Session",    style={**_label_style, "marginBottom": "6px"}),
                          html.Div(id="ana-sess-table")]),
                html.Div([html.Div("By Grade",      style={**_label_style, "marginBottom": "6px"}),
                          html.Div(id="ana-grade-table")]),
                html.Div([html.Div("By Signal Type",style={**_label_style, "marginBottom": "6px"}),
                          html.Div(id="ana-sigtype-table")]),
            ]),

            # Best / worst setups
            html.Div(style={"display": "grid", "gridTemplateColumns": "1fr 1fr",
                             "gap": "16px", "marginBottom": "18px"}, children=[
                html.Div([html.Div("Best Setups (use these)",
                                   style={**_label_style, "color": GREEN, "marginBottom": "6px"}),
                          html.Div(id="ana-best-table")]),
                html.Div([html.Div("Setups to Avoid",
                                   style={**_label_style, "color": RED, "marginBottom": "6px"}),
                          html.Div(id="ana-worst-table")]),
            ]),

            # Indicator contributions + factor correlation
            html.Div(style={"display": "grid", "gridTemplateColumns": "1fr 1fr",
                             "gap": "16px", "marginBottom": "18px"}, children=[
                html.Div([html.Div("Indicator Contribution Scores",
                                   style={**_label_style, "marginBottom": "6px"}),
                          dcc.Graph(id="ana-weight-chart",
                                    style={"height": "260px"},
                                    config={"displayModeBar": False})]),
                html.Div([html.Div("Top Confluence Factors",
                                   style={**_label_style, "marginBottom": "6px"}),
                          html.Div(id="ana-factor-table")]),
            ]),

            # Weight history
            html.Div([html.Div("Learned Weight History",
                               style={**_label_style, "marginBottom": "6px"}),
                      html.Div(id="ana-weight-history")]),
        ]),
    ])


# ── Paper trading tab layout ──────────────────────────────────────────────────

def _paper_layout():
    return html.Div(style={"padding": "4px 0"}, children=[
        # Controls
        html.Div(style={"display": "flex", "gap": "10px", "alignItems": "center",
                        "marginBottom": "16px", "flexWrap": "wrap"}, children=[
            html.Button(id="pt-toggle-btn", n_clicks=0, children="▶  Enable Paper Trading",
                        style={"background": GREEN, "color": "#000", "border": "none",
                               "borderRadius": "6px", "padding": "7px 18px",
                               "fontSize": "13px", "fontWeight": "700", "cursor": "pointer"}),
            html.Button("↺  Refresh", id="pt-refresh-btn", n_clicks=0, style={
                "background": PANEL, "color": DIM, "border": f"1px solid {BORDER}",
                "borderRadius": "6px", "padding": "6px 14px",
                "fontSize": "12px", "cursor": "pointer",
            }),
            html.Button("📄  Weekly Report", id="pt-report-btn", n_clicks=0, style={
                "background": PANEL, "color": BLUE, "border": f"1px solid {BLUE}",
                "borderRadius": "6px", "padding": "6px 14px",
                "fontSize": "12px", "cursor": "pointer",
            }),
            html.Span(id="pt-status-badge"),
        ]),

        # Summary cards
        html.Div(id="pt-summary-row",
                 style={"display": "flex", "gap": "10px",
                        "flexWrap": "wrap", "marginBottom": "18px"}),

        # Open + closed tables
        html.Div(style={"marginBottom": "12px"}, children=[
            html.Div("Open Paper Positions", style={**_label_style, "marginBottom": "6px"}),
            html.Div(id="pt-open-table"),
        ]),
        html.Div(style={"marginBottom": "18px"}, children=[
            html.Div("Closed Paper Trades", style={**_label_style, "marginBottom": "6px"}),
            html.Div(id="pt-closed-table"),
        ]),

        # Weekly report
        html.Div(id="pt-report-container",
                 style={"backgroundColor": PANEL, "border": f"1px solid {BORDER}",
                        "borderRadius": "8px", "padding": "16px", "display": "none"}),

        dcc.Store(id="pt-enabled", data=False),
        dcc.Interval(id="pt-poll", interval=60_000, n_intervals=0),
    ])


# ── Profitability Report tab layout ──────────────────────────────────────────

def _profit_layout():
    def _btn(label, id_, color=BLUE):
        return html.Button(label, id=id_, n_clicks=0, style={
            "background": color, "color": "#000" if color in (BLUE, GOLD) else TEXT,
            "border": f"1px solid {color}", "borderRadius": "6px",
            "padding": "6px 16px", "fontSize": "12px",
            "fontWeight": "600", "cursor": "pointer", "marginRight": "8px",
        })

    return html.Div(style={"padding": "4px 0"}, children=[
        html.Div(style={"display": "flex", "gap": "10px", "alignItems": "center",
                        "marginBottom": "16px", "flexWrap": "wrap"}, children=[
            html.H6("Profitability Report", style={"color": TEXT, "margin": "0"}),
            _btn("↺  Refresh", "prf-refresh-btn"),
            dcc.RadioItems(
                id="prf-mode",
                options=[
                    {"label": "  All Trades",   "value": "all"},
                    {"label": "  Live Only",    "value": "live"},
                    {"label": "  Paper Only",   "value": "paper"},
                ],
                value="all",
                inline=True,
                style={"color": TEXT, "fontSize": "13px", "gap": "20px"},
            ),
        ]),

        dcc.Loading(type="circle", color=BLUE, children=[
            # KPI summary row
            html.Div(id="prf-summary-row",
                     style={"display": "flex", "gap": "10px",
                             "flexWrap": "wrap", "marginBottom": "18px"}),

            # Best/Worst session + setup grid
            html.Div(style={"display": "grid", "gridTemplateColumns": "1fr 1fr",
                             "gap": "16px", "marginBottom": "18px"}, children=[
                html.Div([
                    html.Div("Best Performing Sessions",
                             style={**_label_style, "color": GREEN, "marginBottom": "6px"}),
                    html.Div(id="prf-best-sess"),
                ]),
                html.Div([
                    html.Div("Worst Performing Sessions",
                             style={**_label_style, "color": RED, "marginBottom": "6px"}),
                    html.Div(id="prf-worst-sess"),
                ]),
            ]),

            html.Div(style={"display": "grid", "gridTemplateColumns": "1fr 1fr",
                             "gap": "16px", "marginBottom": "18px"}, children=[
                html.Div([
                    html.Div("Best Setup Types",
                             style={**_label_style, "color": GREEN, "marginBottom": "6px"}),
                    html.Div(id="prf-best-setup"),
                ]),
                html.Div([
                    html.Div("Worst Setup Types",
                             style={**_label_style, "color": RED, "marginBottom": "6px"}),
                    html.Div(id="prf-worst-setup"),
                ]),
            ]),

            # Expectancy breakdown tables
            html.Div(style={"marginBottom": "8px"}, children=[
                html.Div("Expectancy Breakdown  [ E = (WR × Avg Win R) − (LR × Avg Loss R) ]",
                         style={**_label_style, "fontSize": "12px", "marginBottom": "10px"}),
                html.Div(style={"display": "grid", "gridTemplateColumns": "1fr 1fr 1fr 1fr",
                                 "gap": "16px", "marginBottom": "18px"}, children=[
                    html.Div([html.Div("By Session",    style={**_label_style, "marginBottom": "6px"}),
                              html.Div(id="prf-exp-sess")]),
                    html.Div([html.Div("By Timeframe",  style={**_label_style, "marginBottom": "6px"}),
                              html.Div(id="prf-exp-tf")]),
                    html.Div([html.Div("By Grade",      style={**_label_style, "marginBottom": "6px"}),
                              html.Div(id="prf-exp-grade")]),
                    html.Div([html.Div("By Signal Type",style={**_label_style, "marginBottom": "6px"}),
                              html.Div(id="prf-exp-stype")]),
                ]),
            ]),

            # Recommendations
            html.Div([
                html.Div("Filter Recommendations",
                         style={**_label_style, "color": GOLD, "marginBottom": "8px"}),
                html.Div(id="prf-recommendations"),
            ]),
        ]),
    ])


# ── App layout ────────────────────────────────────────────────────────────────

app.layout = html.Div(
    style={"backgroundColor": BG, "minHeight": "100vh",
           "fontFamily": "'Inter', 'SF Pro Display', sans-serif",
           "padding": "16px 24px"},
    children=[
        dcc.Tabs(
            id="main-tabs",
            value="tab-dashboard",
            style={"marginBottom": "16px"},
            colors={"border": BORDER, "primary": BLUE, "background": PANEL},
            children=[
                dcc.Tab(label="Dashboard",       value="tab-dashboard",
                        style=_tab_style, selected_style=_tab_active),
                dcc.Tab(label="Backtester",      value="tab-backtest",
                        style=_tab_style, selected_style=_tab_active),
                dcc.Tab(label="Analytics",       value="tab-analytics",
                        style=_tab_style, selected_style=_tab_active),
                dcc.Tab(label="Paper Trading",   value="tab-paper",
                        style=_tab_style, selected_style=_tab_active),
                dcc.Tab(label="Risk Calculator", value="tab-risk",
                        style=_tab_style, selected_style=_tab_active),
                dcc.Tab(label="Trade Journal",   value="tab-journal",
                        style=_tab_style, selected_style=_tab_active),
                dcc.Tab(label="Profitability",   value="tab-profit",
                        style=_tab_style, selected_style=_tab_active),
            ],
        ),
        html.Div(id="tab-content"),
        _disclaimer_footer,
    ],
)


# ── Tab content renderer ──────────────────────────────────────────────────────

@app.callback(Output("tab-content", "children"), Input("main-tabs", "value"))
def render_tab(tab):
    if tab == "tab-dashboard":
        return _dashboard_layout()
    if tab == "tab-backtest":
        return _backtest_layout()
    if tab == "tab-analytics":
        return _analytics_layout()
    if tab == "tab-paper":
        return _paper_layout()
    if tab == "tab-risk":
        return _risk_layout()
    if tab == "tab-journal":
        return _journal_layout()
    if tab == "tab-profit":
        return _profit_layout()
    return ""


# ── Timeframe button ──────────────────────────────────────────────────────────

@app.callback(
    Output("active-tf", "data"),
    [Input(f"btn-{k}", "n_clicks") for k in TF_LABELS],
    State("active-tf", "data"),
    prevent_initial_call=True,
)
def set_tf(*args):
    ctx = callback_context
    if not ctx.triggered:
        return args[-1]
    return ctx.triggered[0]["prop_id"].split(".")[0].replace("btn-", "")


# ── Main dashboard refresh ────────────────────────────────────────────────────

@app.callback(
    [Output("main-chart",     "figure"),
     Output("price-display",  "children"),
     Output("change-display", "children"),
     Output("signal-display", "children"),
     Output("trade-strip",    "children"),
     Output("info-row",       "children"),
     Output("news-warning",   "children"),
     Output("last-alert-key", "data")],
    [Input("active-tf", "data"), Input("refresh-timer", "n_intervals")],
    State("last-alert-key", "data"),
)
def refresh(tf_key, _, last_alert_key):
    tf_key = tf_key or "swing"
    tf = cfg.TIMEFRAMES[tf_key]

    df = datamod.fetch(interval=tf["interval"], period=tf["period"])
    if df is None or df.empty:
        fig = _empty_fig("No data — market may be closed")
        return fig, "—", "", _signal_pill("NEUTRAL"), "", [], "", last_alert_key

    df  = indicators.add_all(df)
    sig = sig_engine.evaluate(df, tf["label"])

    # ── HTF confirmation ──────────────────────────────────────────────────────
    htf_key = tf.get("htf")
    htf_sig = None
    if htf_key:
        htf_tf = cfg.TIMEFRAMES[htf_key]
        htf_df = datamod.fetch(interval=htf_tf["interval"], period=htf_tf["period"])
        if htf_df is not None and not htf_df.empty:
            htf_df  = indicators.add_all(htf_df)
            htf_sig = sig_engine.evaluate(htf_df, htf_tf["label"])

    sig_engine.add_grade(sig, htf_sig)

    # ── Market context + strict filter ────────────────────────────────────────
    htf_direction = "NEUTRAL"
    if htf_sig:
        if "BUY"  in htf_sig.signal and "NEUTRAL" not in htf_sig.signal:
            htf_direction = "BULL"
        elif "SELL" in htf_sig.signal and "NEUTRAL" not in htf_sig.signal:
            htf_direction = "BEAR"

    try:
        context = mc_mod.classify(df, htf_direction)
    except Exception:
        context = None

    try:
        filter_result = flt_mod.evaluate(sig, df, context)
    except Exception:
        filter_result = None

    if filter_result and filter_result.allowed and sig.grade in ("A", "A+"):
        try:
            sig = sig_engine.enhance_signal(sig, df)
        except Exception:
            pass

    # ── Track open outcomes + open paper trade if enabled ─────────────────────
    sess    = sess_mod.current_session()
    preloaded = {tf_key: df}
    if htf_key and htf_sig is not None:
        htf_df_pre = datamod.fetch(interval=cfg.TIMEFRAMES[htf_key]["interval"],
                                    period=cfg.TIMEFRAMES[htf_key]["period"])
        if htf_df_pre is not None:
            preloaded[htf_key] = indicators.add_all(htf_df_pre)
    try:
        trk_mod.check_all_open(preloaded=preloaded)
    except Exception:
        pass

    alert_key = last_alert_key
    if sig.grade in ("A", "A+") and "NEUTRAL" not in sig.signal and sig.stop_loss and (filter_result is None or filter_result.allowed):
        new_key = f"{sig.signal}|{sig.grade}|{tf_key}|{round(sig.price, -1)}"
        if new_key != last_alert_key:
            # Log to SQLite DB
            try:
                db_mod.log_signal(sig, session=sess["name"], paper=False)
            except Exception:
                pass
            # Log to legacy CSV journal
            journal_mod.log_signal(sig)
            # Open paper trade if mode enabled
            if pt_mod.is_enabled():
                try:
                    pt_mod.open_trade(sig, session=sess["name"])
                except Exception:
                    pass
            # Send alerts
            alert_mod.send_if_notable(sig)
            alert_key = new_key

    # ── ML confidence badge ───────────────────────────────────────────────────
    ml_badge = ""
    if "NEUTRAL" not in sig.signal and sig.stop_loss:
        try:
            pred = ml_model.predict(sig, session=sess["name"])
            if pred.features_available:
                pct  = round(pred.confidence * 100)
                c    = GREEN if pct >= 60 else (GOLD if pct >= 45 else RED)
                ml_badge = html.Div(style={
                    "display": "flex", "flexDirection": "column",
                    "alignItems": "center", "backgroundColor": PANEL,
                    "border": f"1px solid {BORDER}", "borderRadius": "6px",
                    "padding": "4px 12px",
                }, children=[
                    html.Span(f"ML: {pct}%",
                              style={"color": c, "fontSize": "13px", "fontWeight": "700"}),
                    html.Span("model estimate", style={"color": DIM, "fontSize": "9px"}),
                ])
        except Exception:
            pass

    # ── Price / change ────────────────────────────────────────────────────────
    price      = sig.price
    prev_close = float(df["close"].iloc[-2]) if len(df) > 1 else price
    chg        = price - prev_close
    chg_pct    = chg / prev_close * 100

    price_el  = f"{price:,.2f}"
    change_el = html.Span(
        f"{'▲' if chg >= 0 else '▼'} {abs(chg):,.1f}  ({abs(chg_pct):.2f}%)",
        style={"color": GREEN if chg >= 0 else RED},
    )

    # ── Info row ──────────────────────────────────────────────────────────────
    info_items = []

    # Grade badge
    if sig.grade:
        grade_colors = {"A+": (GOLD, "#2b240d"), "A": (GREEN, "#0d2b1a"),
                        "B": (BLUE, "#0d1a2b"), "C": (MUTED, PANEL)}
        gc, gb = grade_colors.get(sig.grade, (DIM, PANEL))
        info_items.append(_pill(f"Grade: {sig.grade}", gc, gb, "12px"))

    if ml_badge:
        info_items.append(ml_badge)

    # MTF badge
    if htf_sig and "NEUTRAL" not in sig.signal:
        if sig.mtf_confirmed:
            info_items.append(_pill(f"HTF ✓ {TF_LABELS.get(htf_key, htf_key)} confirms", GREEN, "#0d2b1a", "12px"))
        else:
            info_items.append(_pill(f"HTF ✗ {TF_LABELS.get(htf_key, htf_key)} disagrees", RED, "#2b0d0d", "12px"))

    # Confluence score
    confluence = max(sig.bull_score, sig.bear_score)
    if confluence > 0:
        score_color = GREEN if "BUY" in sig.signal else (RED if "SELL" in sig.signal else DIM)
        info_items.append(html.Div(
            f"Confluence score: {confluence:.0f}/100",
            style={"color": score_color, "fontSize": "12px",
                   "border": f"1px solid {BORDER}", "borderRadius": "6px",
                   "padding": "4px 12px", "backgroundColor": PANEL},
        ))

    # Market context badge
    if context is not None:
        regime_cfg = {
            "TRENDING_BULL": (GREEN,  "#0d2b1a"),
            "TRENDING_BEAR": (RED,    "#2b0d0d"),
            "RANGING":       (BLUE,   "#0d1a2b"),
            "CHOPPY":        (GOLD,   "#2b240d"),
            "VOLATILE":      (PURPLE, "#1a0d2b"),
            "LOW_VOL":       (DIM,    PANEL),
        }
        rc, rb = regime_cfg.get(context.regime, (DIM, PANEL))
        info_items.append(_pill(
            f"{context.regime.replace('_', ' ')}  ADX {context.adx:.0f}",
            rc, rb, "12px"
        ))

    # Filter status badge
    if filter_result is not None and not filter_result.allowed:
        info_items.append(html.Div(
            f"⊗  {filter_result.reason}",
            style={"color": RED, "fontSize": "12px",
                   "border": f"1px solid {RED}40",
                   "borderRadius": "6px", "padding": "4px 12px",
                   "backgroundColor": "#2b0d0d"},
        ))
    for w in (filter_result.warnings if filter_result else []):
        info_items.append(html.Span(
            f"⚠ {w}", style={"color": GOLD, "fontSize": "11px"},
        ))

    # Session badge
    sess_icon = "◉" if sess["tradeable"] else "○"
    info_items.append(html.Div(
        f"{sess_icon}  {sess['name']}",
        style={"color": sess["color"], "fontSize": "12px",
               "border": f"1px solid {sess['color']}40",
               "borderRadius": "6px", "padding": "4px 12px",
               "backgroundColor": PANEL},
    ))
    if not sess["tradeable"] and "NEUTRAL" not in sig.signal:
        info_items.append(html.Span(
            "⚠ Low-quality session — consider waiting for NY Open or Power Hour",
            style={"color": GOLD, "fontSize": "11px"},
        ))

    # ── News warning ──────────────────────────────────────────────────────────
    events = news_mod.get_upcoming_events(hours_ahead=24)
    news_el = ""
    if events:
        event_rows = [
            html.Div(f"📅  {e['title']}  —  {e['date_str']}", style={"marginBottom": "2px"})
            for e in events
        ]
        news_el = html.Div(style={
            "backgroundColor": "#1a150a", "border": f"1px solid {GOLD}",
            "borderRadius": "6px", "padding": "10px 16px",
            "color": GOLD, "fontSize": "12px",
        }, children=[
            html.Strong("⚠  High-Impact Events in Next 24 Hours — Trade Carefully",
                        style={"display": "block", "marginBottom": "6px"}),
            *event_rows,
        ])

    # ── Chart + trade strip ───────────────────────────────────────────────────
    if filter_result is not None and not filter_result.allowed:
        trade_el = html.Div(style={
            "backgroundColor": "#1a0a0a", "border": f"1px solid {RED}",
            "borderRadius": "8px", "padding": "10px 20px",
            "color": RED, "fontSize": "13px", "fontWeight": "600",
            "display": "inline-block",
        }, children=f"⊗  {filter_result.reason}")
    else:
        trade_el = _trade_strip(sig)
    fig      = build_chart(df, sig, tf_key)

    return (fig, price_el, change_el, _signal_pill(sig.signal),
            trade_el, info_items, news_el, alert_key)


# ── Signal pill ───────────────────────────────────────────────────────────────

def _signal_pill(signal: str):
    cfg_map = {
        "STRONG BUY":  (GREEN,  "#0d2b1a"),
        "BUY":         (GREEN,  "#0d2b1a"),
        "NEUTRAL":     (GOLD,   "#2b240d"),
        "SELL":        (RED,    "#2b0d0d"),
        "STRONG SELL": (RED,    "#2b0d0d"),
    }
    color, bg = cfg_map.get(signal, (DIM, PANEL))
    return html.Div(signal, style={
        "backgroundColor": bg, "color": color,
        "border": f"1px solid {color}",
        "borderRadius": "6px", "padding": "6px 18px",
        "fontSize": "13px", "fontWeight": "700", "letterSpacing": "0.06em",
        "display": "inline-block",
    })


# ── Trade idea strip ──────────────────────────────────────────────────────────

def _trade_strip(sig):
    if not sig.stop_loss or not sig.target or "NEUTRAL" in sig.signal:
        return ""
    if sig.risk_reward < cfg.RISK_REWARD_MIN:
        return ""

    is_long  = "BUY" in sig.signal
    dir_col  = GREEN if is_long else RED
    dir_text = "LONG" if is_long else "SHORT"

    def pill(label, value, color):
        return html.Div([
            html.Span(label, style={"color": DIM, "fontSize": "10px",
                                    "display": "block", "marginBottom": "2px",
                                    "letterSpacing": "0.06em"}),
            html.Span(value, style={"color": color, "fontSize": "15px", "fontWeight": "600"}),
        ], style={"textAlign": "center"})

    items = [
        html.Div(dir_text, style={"color": dir_col, "fontWeight": "700",
                                   "fontSize": "13px", "letterSpacing": "0.08em"}),
        pill("ENTRY",  f"{sig.price:,.1f}",       TEXT),
        pill("STOP",   f"{sig.stop_loss:,.1f}",   RED),
    ]

    if sig.partial_tp1 > 0:
        items.append(pill("TP1 (50%)", f"{sig.partial_tp1:,.1f}", GOLD))
    if sig.partial_tp2 > 0:
        items.append(pill("TP2 (50%)", f"{sig.partial_tp2:,.1f}", GREEN))
    else:
        items.append(pill("TARGET", f"{sig.target:,.1f}", GREEN))

    rr_label = (f"{sig.partial_rr_model:.1f}R*" if sig.partial_rr_model > 0
                else f"{sig.risk_reward:.1f}x")
    items.append(pill("R : R",  rr_label, GOLD))

    if sig.stop_type == "STRUCTURE":
        items.append(html.Span("struct stop", style={"color": DIM, "fontSize": "10px"}))
    if sig.entry_type:
        items.append(html.Span(sig.entry_type, style={"color": BLUE, "fontSize": "10px"}))

    return html.Div(style={
        "backgroundColor": PANEL, "border": f"1px solid {BORDER}",
        "borderRadius": "8px", "padding": "10px 20px",
        "display": "inline-flex", "alignItems": "center", "gap": "24px",
        "flexWrap": "wrap",
    }, children=items)


# ── Main chart ────────────────────────────────────────────────────────────────

def build_chart(df: pd.DataFrame, sig, tf_key: str) -> go.Figure:
    display_df = df.iloc[-120:].copy()
    xs = display_df.index

    fig = make_subplots(rows=2, cols=1, shared_xaxes=True,
                        row_heights=[0.82, 0.18], vertical_spacing=0.012)

    fig.add_trace(go.Candlestick(
        x=xs, open=display_df["open"], high=display_df["high"],
        low=display_df["low"], close=display_df["close"],
        increasing_line_color=GREEN, decreasing_line_color=RED,
        increasing_fillcolor=GREEN,  decreasing_fillcolor=RED,
        name="NQ", line=dict(width=1),
    ), row=1, col=1)

    bar_colors = [
        f"rgba(38,166,91,{0.5 if c >= o else 0.15})" if c >= o
        else f"rgba(232,64,64,{0.5 if c < o else 0.15})"
        for c, o in zip(display_df["close"], display_df["open"])
    ]
    fig.add_trace(go.Bar(x=xs, y=display_df["volume"],
                         marker_color=bar_colors, showlegend=False), row=2, col=1)

    sh, sl = liq.swing_points(display_df, left=5, right=5)
    if not sh.empty:
        fig.add_trace(go.Scatter(x=sh.index, y=sh["level"] * 1.00025, mode="markers",
                                  marker=dict(symbol="triangle-down", color=RED, size=7, opacity=0.8),
                                  showlegend=False, hovertemplate="SH %{y:,.1f}<extra></extra>"),
                      row=1, col=1)
    if not sl.empty:
        fig.add_trace(go.Scatter(x=sl.index, y=sl["level"] * 0.99975, mode="markers",
                                  marker=dict(symbol="triangle-up", color=GREEN, size=7, opacity=0.8),
                                  showlegend=False, hovertemplate="SL %{y:,.1f}<extra></extra>"),
                      row=1, col=1)

    eq_lvls = liq.equal_levels(sh, sl)
    eq_near = sorted(eq_lvls, key=lambda e: abs(e["level"] - sig.price))[:6]
    for eq in eq_near:
        is_high = eq["kind"] == "EQH"
        color   = "rgba(232,64,64,0.45)" if is_high else "rgba(38,166,91,0.45)"
        fig.add_hline(y=eq["level"], line=dict(color=color, width=1, dash="dot"),
                       annotation_text=eq["kind"],
                       annotation_font_color=RED if is_high else GREEN,
                       annotation_font_size=9, annotation_xanchor="left", row=1, col=1)

    for ob in liq.order_blocks(display_df):
        is_bull  = ob["kind"] == "bull_ob"
        fig.add_hrect(
            y0=ob["bottom"], y1=ob["top"],
            fillcolor="rgba(38,166,91,0.08)"  if is_bull else "rgba(232,64,64,0.08)",
            line=dict(color="rgba(38,166,91,0.5)" if is_bull else "rgba(232,64,64,0.5)", width=1),
            annotation_text="OB ▲" if is_bull else "OB ▼",
            annotation_font_color=GREEN if is_bull else RED,
            annotation_font_size=9, annotation_xanchor="left", row=1, col=1,
        )

    vp       = liq.volume_profile(display_df, bins=36)
    max_vol  = vp["volume"].max()
    p_range  = display_df["high"].max() - display_df["low"].min()
    bin_half = p_range / (2 * len(vp))
    hvn_q    = vp["volume"].quantile(0.80)
    if max_vol > 0:
        for _, row_vp in vp.iterrows():
            norm   = row_vp["volume"] / max_vol
            is_hvn = row_vp["volume"] >= hvn_q
            fig.add_shape(
                type="rect", xref="paper", yref="y1",
                x0=1.0 - norm * 0.07, x1=1.0,
                y0=row_vp["price_mid"] - bin_half, y1=row_vp["price_mid"] + bin_half,
                fillcolor="rgba(38,166,91,0.45)" if is_hvn else "rgba(40,40,60,0.5)",
                line_width=0,
            )

    if sig.stop_loss and sig.target and "NEUTRAL" not in sig.signal:
        for y_val, color, label in [
            (sig.price,     BLUE,  f"Entry  {sig.price:,.1f}"),
            (sig.stop_loss, RED,   f"Stop  {sig.stop_loss:,.1f}"),
            (sig.target,    GREEN, f"Target  {sig.target:,.1f}"),
        ]:
            fig.add_hline(y=y_val,
                           line=dict(color=color, width=1.5,
                                     dash="solid" if y_val == sig.price else "dash"),
                           annotation_text=label, annotation_font_color=color,
                           annotation_font_size=10, annotation_xanchor="right",
                           row=1, col=1)
        fig.add_hrect(y0=min(sig.price, sig.stop_loss), y1=max(sig.price, sig.stop_loss),
                       fillcolor="rgba(232,64,64,0.06)", line_width=0, row=1, col=1)
        fig.add_hrect(y0=min(sig.price, sig.target), y1=max(sig.price, sig.target),
                       fillcolor="rgba(38,166,91,0.06)", line_width=0, row=1, col=1)

    axis_common = dict(gridcolor=BORDER, zerolinecolor=BORDER,
                       tickfont=dict(size=10, color=DIM),
                       showline=False, zeroline=False)
    fig.update_layout(
        paper_bgcolor=BG, plot_bgcolor=PANEL,
        font=dict(color=TEXT, family="'Inter', sans-serif"),
        margin=dict(l=0, r=0, t=0, b=0),
        xaxis_rangeslider_visible=False,
        showlegend=False,
        hovermode="x unified",
        hoverlabel=dict(bgcolor=PANEL, font_size=12, font_color=TEXT, bordercolor=BORDER),
        xaxis=dict(**axis_common, showspikes=True, spikecolor=MUTED, spikethickness=1, spikedash="dot"),
        yaxis=dict(**axis_common, side="right", tickformat=",.0f"),
        xaxis2=dict(**axis_common),
        yaxis2=dict(**axis_common, showticklabels=False),
    )
    return fig


def _empty_fig(msg: str) -> go.Figure:
    fig = go.Figure()
    fig.update_layout(
        paper_bgcolor=BG, plot_bgcolor=PANEL,
        font=dict(color=DIM),
        annotations=[dict(text=msg, showarrow=False, font=dict(size=14, color=DIM),
                          xref="paper", yref="paper", x=0.5, y=0.5)],
        margin=dict(l=0, r=0, t=0, b=0),
    )
    return fig


# ── Backtest callback ─────────────────────────────────────────────────────────

import backtest as bt_mod

@app.callback(
    [Output("bt-stats-row",    "children"),
     Output("bt-by-signal",    "children"),
     Output("bt-equity-chart", "figure"),
     Output("bt-trade-table",  "children")],
    Input("bt-run-btn", "n_clicks"),
    State("bt-tf-select", "value"),
    prevent_initial_call=True,
)
def run_backtest(n_clicks, tf_key):
    result = bt_mod.run(tf_key or "swing")

    if result.get("error") and not result["trades"]:
        return (
            html.Span(result["error"], style={"color": RED}),
            "", _empty_fig(result["error"]), "",
        )

    stats = result.get("stats", {})
    if not stats:
        return (
            html.Span(result.get("error", "No completed trades"), style={"color": GOLD}),
            "", _empty_fig("No completed trades"), "",
        )

    wr_color = GREEN if stats["win_rate"] >= 50 else RED
    pf_color = GREEN if str(stats["profit_factor"]) != "0" and stats["net_r"] > 0 else RED

    stats_row = [
        _stat_card("Win Rate",     f"{stats['win_rate']}%",      wr_color),
        _stat_card("Avg R:R",      f"{stats['avg_rr']}x",        GOLD),
        _stat_card("Profit Factor",str(stats['profit_factor']),  pf_color),
        _stat_card("Max DD",       f"{stats['max_drawdown_r']}R", RED),
        _stat_card("Net R",        f"{stats['net_r']}R",          GREEN if stats["net_r"] > 0 else RED),
        _stat_card("Trades",       f"{stats['total_trades']}",    DIM),
        _stat_card("Wins / Losses",f"{stats['wins']} / {stats['losses']}", DIM),
    ]

    # By-signal breakdown
    by_sig = result.get("by_signal", {})
    sig_rows = []
    for sig_name, d in by_sig.items():
        sig_rows.append(html.Tr([
            html.Td(sig_name, style={"color": TEXT, "padding": "4px 12px"}),
            html.Td(str(d["trades"]), style={"color": DIM, "padding": "4px 12px", "textAlign": "right"}),
            html.Td(f"{d['win_rate']}%", style={"color": GREEN if d["win_rate"] >= 50 else RED,
                                                  "padding": "4px 12px", "textAlign": "right"}),
        ]))
    by_sig_table = html.Table([
        html.Thead(html.Tr([
            html.Th("Signal", style={"color": DIM, "padding": "4px 12px", "textAlign": "left"}),
            html.Th("Trades", style={"color": DIM, "padding": "4px 12px", "textAlign": "right"}),
            html.Th("Win Rate", style={"color": DIM, "padding": "4px 12px", "textAlign": "right"}),
        ])),
        html.Tbody(sig_rows),
    ], style={"borderCollapse": "collapse", "backgroundColor": PANEL,
              "border": f"1px solid {BORDER}", "borderRadius": "6px"}) if sig_rows else ""

    # Equity curve
    curve = result.get("equity_curve", [])
    if curve:
        colors = [GREEN if v >= 0 else RED for v in curve]
        eq_fig = go.Figure(go.Scatter(
            y=curve, mode="lines+markers",
            line=dict(color=BLUE, width=2),
            marker=dict(size=5, color=colors),
            hovertemplate="Trade %{x+1}: %{y:.2f}R<extra></extra>",
        ))
        eq_fig.add_hline(y=0, line=dict(color=BORDER, width=1, dash="dot"))
        eq_fig.update_layout(
            paper_bgcolor=BG, plot_bgcolor=PANEL,
            font=dict(color=TEXT), margin=dict(l=0, r=0, t=24, b=0),
            title=dict(text="Equity Curve (R-multiples)", font=dict(size=12, color=DIM), x=0),
            xaxis=dict(gridcolor=BORDER, tickfont=dict(color=DIM), zeroline=False),
            yaxis=dict(gridcolor=BORDER, tickfont=dict(color=DIM), zeroline=False),
        )
    else:
        eq_fig = _empty_fig("No equity curve data")

    # Trade log table
    trades = result.get("trades", [])
    if trades:
        completed_trades = [t for t in trades if t["outcome"] in ("WIN", "LOSS", "OPEN")]
        trade_table = dash_table.DataTable(
            data=completed_trades,
            columns=[{"name": c.upper(), "id": c}
                     for c in ["time", "signal", "entry", "stop", "target", "rr", "outcome", "pnl_r"]],
            style_table={"overflowX": "auto"},
            style_header={"backgroundColor": BORDER, "color": DIM, "fontWeight": "600",
                          "fontSize": "11px", "border": f"1px solid {BORDER}"},
            style_cell={"backgroundColor": PANEL, "color": TEXT, "fontSize": "12px",
                        "border": f"1px solid {BORDER}", "padding": "6px 10px"},
            style_data_conditional=[
                {"if": {"filter_query": "{outcome} = WIN"},  "color": GREEN},
                {"if": {"filter_query": "{outcome} = LOSS"}, "color": RED},
            ],
            page_size=20,
        )
    else:
        trade_table = html.Span("No trades to display.", style={"color": DIM})

    return stats_row, by_sig_table, eq_fig, trade_table


# ── Risk calculator callback ──────────────────────────────────────────────────

@app.callback(
    Output("rc-results", "children"),
    [Input("rc-account", "value"),
     Input("rc-risk-pct", "value"),
     Input("rc-max-loss", "value"),
     Input("rc-entry", "value"),
     Input("rc-stop", "value"),
     Input("rc-contract-type", "value")],
)
def compute_risk(account, risk_pct, max_loss, entry, stop, contract_type):
    try:
        account   = float(account or cfg.DEFAULT_ACCOUNT_SIZE)
        risk_pct  = float(risk_pct  or cfg.DEFAULT_RISK_PCT)
        max_loss  = float(max_loss  or cfg.DEFAULT_MAX_LOSS)
        entry     = float(entry or 0)
        stop      = float(stop  or 0)
    except (TypeError, ValueError):
        return html.Span("Enter valid numbers", style={"color": DIM})

    pt_val = cfg.NQ_POINT_VALUE if contract_type == "NQ" else cfg.MNQ_POINT_VALUE

    risk_from_pct = account * risk_pct / 100
    dollar_risk   = min(risk_from_pct, max_loss)

    if entry > 0 and stop > 0 and entry != stop:
        stop_pts     = abs(entry - stop)
        dollar_per_c = stop_pts * pt_val
        contracts    = max(1, int(dollar_risk / dollar_per_c)) if dollar_per_c > 0 else 0
        actual_risk  = contracts * dollar_per_c
        profit_1r    = actual_risk * 2   # 2R target
        profit_2r    = actual_risk * 3   # 3R target
    else:
        stop_pts = contracts = actual_risk = profit_1r = profit_2r = 0

    def row(label, value, color=TEXT):
        return html.Div(style={"display": "flex", "justifyContent": "space-between",
                                "padding": "4px 0", "borderBottom": f"1px solid {BORDER}"}, children=[
            html.Span(label, style={"color": DIM, "fontSize": "12px"}),
            html.Span(value, style={"color": color, "fontSize": "13px", "fontWeight": "600"}),
        ])

    return html.Div(style={
        "backgroundColor": PANEL, "border": f"1px solid {BORDER}",
        "borderRadius": "8px", "padding": "14px 16px",
    }, children=[
        row("Max $ Risk",         f"${dollar_risk:,.0f}", GOLD),
        row("Stop Distance",      f"{stop_pts:.2f} pts"   if stop_pts else "—", DIM),
        row(f"Contracts ({contract_type})", str(contracts) if contracts else "—",
            GREEN if contracts else DIM),
        row("Actual $ Risk",      f"${actual_risk:,.0f}"  if actual_risk else "—", RED),
        row("2R Profit Target",   f"${profit_1r:,.0f}"    if profit_1r  else "—", GREEN),
        row("3R Profit Target",   f"${profit_2r:,.0f}"    if profit_2r  else "—", GREEN),
    ])


# ── Trade journal callbacks ───────────────────────────────────────────────────

@app.callback(
    [Output("jrn-table-container", "children"),
     Output("jrn-store", "data")],
    Input("jrn-refresh-btn", "n_clicks"),
)
def load_journal(_):
    rows = journal_mod.load_journal()
    if not rows:
        return html.Span("No trades logged yet. A/A+ signals are auto-logged.",
                         style={"color": DIM, "fontSize": "13px"}), []

    table = dash_table.DataTable(
        id="jrn-datatable",
        data=rows,
        columns=[{"name": c.replace("_", " ").upper(), "id": c,
                  "editable": c in ("outcome", "pnl_pts")}
                 for c in journal_mod.FIELDS],
        style_table={"overflowX": "auto"},
        style_header={"backgroundColor": BORDER, "color": DIM,
                       "fontWeight": "600", "fontSize": "11px",
                       "border": f"1px solid {BORDER}"},
        style_cell={"backgroundColor": PANEL, "color": TEXT, "fontSize": "12px",
                    "border": f"1px solid {BORDER}", "padding": "6px 10px",
                    "maxWidth": "220px", "overflow": "hidden", "textOverflow": "ellipsis"},
        style_data_conditional=[
            {"if": {"filter_query": "{outcome} = WIN"},  "color": GREEN},
            {"if": {"filter_query": "{outcome} = LOSS"}, "color": RED},
            {"if": {"column_id": "outcome"}, "backgroundColor": "#1a1a28",
             "border": f"1px solid {BLUE}"},
            {"if": {"column_id": "pnl_pts"}, "backgroundColor": "#1a1a28",
             "border": f"1px solid {BLUE}"},
        ],
        editable=True,
        page_size=25,
        sort_action="native",
        filter_action="native",
        tooltip_data=[{c: {"value": str(row.get(c, "")), "type": "text"}
                       for c in journal_mod.FIELDS} for row in rows],
        tooltip_duration=None,
    )
    return table, rows


@app.callback(
    Output("jrn-store", "data", allow_duplicate=True),
    Input("jrn-datatable", "data"),
    prevent_initial_call=True,
)
def save_journal_edits(data):
    if data:
        journal_mod.save_journal(data)
    return data


@app.callback(
    Output("jrn-download", "data"),
    Input("jrn-export-btn", "n_clicks"),
    State("jrn-store", "data"),
    prevent_initial_call=True,
)
def export_journal(_, data):
    if not data:
        return None
    df_out = pd.DataFrame(data, columns=journal_mod.FIELDS)
    return dcc.send_data_frame(df_out.to_csv, "nqb_trade_journal.csv", index=False)


# ── Analytics callbacks ───────────────────────────────────────────────────────

def _make_wr_table(rows: list[dict], key: str) -> dash_table.DataTable | html.Span:
    if not rows:
        return html.Span("No data yet.", style={"color": DIM, "fontSize": "12px"})
    return dash_table.DataTable(
        data=rows,
        columns=[{"name": c.replace("_", " ").upper(), "id": c}
                 for c in [key, "trades", "win_rate", "avg_rr"]],
        style_table={"overflowX": "auto"},
        style_header={"backgroundColor": BORDER, "color": DIM,
                       "fontWeight": "600", "fontSize": "10px",
                       "border": f"1px solid {BORDER}"},
        style_cell={"backgroundColor": PANEL, "color": TEXT, "fontSize": "11px",
                    "border": f"1px solid {BORDER}", "padding": "4px 8px"},
        style_data_conditional=[
            {"if": {"filter_query": "{win_rate} >= 55"}, "color": GREEN},
            {"if": {"filter_query": "{win_rate} < 45"},  "color": RED},
        ],
        sort_action="native",
        page_size=10,
    )


@app.callback(
    [Output("ana-summary-row",     "children"),
     Output("ana-tf-table",        "children"),
     Output("ana-sess-table",      "children"),
     Output("ana-grade-table",     "children"),
     Output("ana-sigtype-table",   "children"),
     Output("ana-best-table",      "children"),
     Output("ana-worst-table",     "children"),
     Output("ana-weight-chart",    "figure"),
     Output("ana-factor-table",    "children"),
     Output("ana-weight-history",  "children"),
     Output("ana-status",          "children")],
    [Input("ana-refresh-btn",   "n_clicks"),
     Input("ana-weight-btn",    "n_clicks"),
     Input("ana-ml-train-btn",  "n_clicks")],
    prevent_initial_call=False,
)
def refresh_analytics(n_refresh, n_weight, n_ml):
    ctx = callback_context
    status_msg = ""

    # Run weight update if requested
    if ctx.triggered and "ana-weight-btn" in ctx.triggered[0]["prop_id"]:
        try:
            result = learn_mod.run_walk_forward(force=True)
            if result.get("status") == "updated":
                tw = result.get("test_win_rate", 0)
                status_msg = (f"Weights updated  |  test win-rate: {tw}%  |  "
                               f"train: {result.get('n_train')} / test: {result.get('n_test')} trades")
            else:
                status_msg = result.get("reason", "No update needed")
        except Exception as e:
            status_msg = f"Weight update error: {e}"

    # Train ML model if requested
    if ctx.triggered and "ana-ml-train-btn" in ctx.triggered[0]["prop_id"]:
        try:
            result = ml_model.train_and_save()
            status_msg = (f"ML ({result.get('model_type','')}) trained on "
                           f"{result.get('n_train',0)} trades  |  "
                           f"base win-rate: {result.get('win_rate',0)}%"
                           if result.get("status") == "trained"
                           else result.get("reason", "Cannot train yet"))
        except Exception as e:
            status_msg = f"ML training error: {e}"

    trades = db_mod.get_completed_trades()

    # Summary row
    stats      = ana_mod.overall_stats(trades)
    summary_row = []
    if stats:
        wr_c = GREEN if stats.get("win_rate", 0) >= 50 else RED
        summary_row = [
            _stat_card("Total Trades",   str(stats.get("total", 0))),
            _stat_card("Win Rate",        f"{stats.get('win_rate',0)}%",     wr_c),
            _stat_card("Net R",           str(stats.get("net_r", 0)),
                        GREEN if (stats.get("net_r") or 0) > 0 else RED),
            _stat_card("Profit Factor",   str(stats.get("profit_factor") or "—")),
            _stat_card("Avg MFE",         f"{stats.get('avg_mfe_pts',0)} pts"),
            _stat_card("Avg MAE",         f"{stats.get('avg_mae_pts',0)} pts"),
        ]
    else:
        summary_row = [html.Span("No completed trades yet — signals are auto-logged as they occur.",
                                  style={"color": DIM, "fontSize": "13px"})]

    # Breakdown tables
    tf_table    = _make_wr_table(ana_mod.win_rate_table("timeframe", trades),   "timeframe")
    sess_table  = _make_wr_table(ana_mod.win_rate_table("session",   trades),   "session")
    grade_table = _make_wr_table(ana_mod.win_rate_table("grade",     trades),   "grade")
    stype_table = _make_wr_table(ana_mod.win_rate_table("signal_type",trades),  "signal_type")

    # Best / worst
    best_rows  = ana_mod.best_setups(trades, top_n=6)
    worst_rows = ana_mod.worst_setups(trades, top_n=6)

    def _setup_table(rows, key_color):
        if not rows:
            return html.Span("Need more data.", style={"color": DIM, "fontSize": "12px"})
        return dash_table.DataTable(
            data=rows,
            columns=[{"name": c.upper(), "id": c}
                     for c in ["setup", "trades", "win_rate", "avg_r"]],
            style_table={"overflowX": "auto"},
            style_header={"backgroundColor": BORDER, "color": DIM,
                           "fontWeight": "600", "fontSize": "10px",
                           "border": f"1px solid {BORDER}"},
            style_cell={"backgroundColor": PANEL, "color": TEXT, "fontSize": "11px",
                        "border": f"1px solid {BORDER}", "padding": "4px 8px",
                        "maxWidth": "280px", "overflow": "hidden",
                        "textOverflow": "ellipsis"},
            style_data_conditional=[
                {"if": {"column_id": "win_rate"}, "color": key_color}
            ],
            page_size=6,
        )

    best_table  = _setup_table(best_rows,  GREEN)
    worst_table = _setup_table(worst_rows, RED)

    # Indicator contribution chart
    contrib     = ana_mod.indicator_contribution(trades)
    weight_fig  = _empty_fig("No trade data for indicator analysis")
    if contrib:
        names   = list(contrib.keys())
        scores  = [contrib[n].get("contribution_score", 0) * 100 for n in names]
        colors  = [GREEN if s >= 0 else RED for s in scores]
        current_w = learn_mod.get_current_weights()
        bar_text  = [f"w={current_w.get(n, 0):.3f}" for n in names]

        weight_fig = go.Figure(go.Bar(
            x=names, y=scores, marker_color=colors,
            text=bar_text, textposition="outside",
            hovertemplate="%{x}: contribution %{y:.1f}%<extra></extra>",
        ))
        weight_fig.add_hline(y=0, line=dict(color=BORDER, width=1))
        weight_fig.update_layout(
            paper_bgcolor=BG, plot_bgcolor=PANEL,
            font=dict(color=TEXT), margin=dict(l=0, r=0, t=24, b=0),
            title=dict(text="Contribution score & current weight", font=dict(size=11, color=DIM)),
            xaxis=dict(gridcolor=BORDER, tickfont=dict(color=DIM, size=10)),
            yaxis=dict(gridcolor=BORDER, tickfont=dict(color=DIM), title="% above chance"),
        )

    # Factor correlation table
    factors     = ana_mod.factor_correlation(trades)
    factor_table = html.Span("Need more data.", style={"color": DIM, "fontSize": "12px"})
    if factors:
        factor_table = dash_table.DataTable(
            data=factors[:15],
            columns=[{"name": c.upper(), "id": c}
                     for c in ["reason", "appearances", "win_rate"]],
            style_table={"overflowX": "auto"},
            style_header={"backgroundColor": BORDER, "color": DIM,
                           "fontWeight": "600", "fontSize": "10px",
                           "border": f"1px solid {BORDER}"},
            style_cell={"backgroundColor": PANEL, "color": TEXT, "fontSize": "11px",
                        "border": f"1px solid {BORDER}", "padding": "4px 8px",
                        "maxWidth": "300px", "overflow": "hidden",
                        "textOverflow": "ellipsis"},
            style_data_conditional=[
                {"if": {"filter_query": "{win_rate} >= 55"}, "color": GREEN},
                {"if": {"filter_query": "{win_rate} < 45"},  "color": RED},
            ],
            page_size=10,
        )

    # Weight history
    wh = learn_mod.weight_history_table()
    wh_table = html.Span("No weight updates yet.", style={"color": DIM, "fontSize": "12px"})
    if wh:
        wh_table = dash_table.DataTable(
            data=wh,
            columns=[{"name": c.upper(), "id": c}
                     for c in ["indicator", "initial", "current", "total_change", "last_test_wr", "updates"]],
            style_table={"overflowX": "auto"},
            style_header={"backgroundColor": BORDER, "color": DIM,
                           "fontWeight": "600", "fontSize": "10px",
                           "border": f"1px solid {BORDER}"},
            style_cell={"backgroundColor": PANEL, "color": TEXT, "fontSize": "11px",
                        "border": f"1px solid {BORDER}", "padding": "4px 8px"},
            style_data_conditional=[
                {"if": {"filter_query": "{total_change} > 0"}, "color": GREEN},
                {"if": {"filter_query": "{total_change} < 0"}, "color": RED},
            ],
        )

    return (summary_row, tf_table, sess_table, grade_table, stype_table,
            best_table, worst_table, weight_fig, factor_table, wh_table, status_msg)


# ── Paper trading callbacks ───────────────────────────────────────────────────

def _trade_rows_table(rows: list[dict], columns: list[str]) -> dash_table.DataTable | html.Span:
    if not rows:
        return html.Span("No trades.", style={"color": DIM, "fontSize": "12px"})
    return dash_table.DataTable(
        data=rows,
        columns=[{"name": c.replace("_", " ").upper(), "id": c} for c in columns],
        style_table={"overflowX": "auto"},
        style_header={"backgroundColor": BORDER, "color": DIM,
                       "fontWeight": "600", "fontSize": "10px",
                       "border": f"1px solid {BORDER}"},
        style_cell={"backgroundColor": PANEL, "color": TEXT, "fontSize": "11px",
                    "border": f"1px solid {BORDER}", "padding": "4px 8px",
                    "maxWidth": "160px", "overflow": "hidden", "textOverflow": "ellipsis"},
        style_data_conditional=[
            {"if": {"filter_query": "{outcome} = WIN"},  "color": GREEN},
            {"if": {"filter_query": "{outcome} = LOSS"}, "color": RED},
        ],
        page_size=15, sort_action="native",
    )


@app.callback(
    Output("pt-enabled", "data"),
    Output("pt-toggle-btn", "children"),
    Output("pt-toggle-btn", "style"),
    Input("pt-toggle-btn", "n_clicks"),
    State("pt-enabled", "data"),
    prevent_initial_call=True,
)
def toggle_paper_trading(_, enabled):
    new_state = not bool(enabled)
    if new_state:
        pt_mod.enable()
        label = "■  Disable Paper Trading"
        style = {"background": RED, "color": TEXT, "border": "none",
                 "borderRadius": "6px", "padding": "7px 18px",
                 "fontSize": "13px", "fontWeight": "700", "cursor": "pointer"}
    else:
        pt_mod.disable()
        label = "▶  Enable Paper Trading"
        style = {"background": GREEN, "color": "#000", "border": "none",
                 "borderRadius": "6px", "padding": "7px 18px",
                 "fontSize": "13px", "fontWeight": "700", "cursor": "pointer"}
    return new_state, label, style


@app.callback(
    [Output("pt-summary-row",  "children"),
     Output("pt-status-badge", "children"),
     Output("pt-open-table",   "children"),
     Output("pt-closed-table", "children")],
    [Input("pt-refresh-btn", "n_clicks"),
     Input("pt-poll",        "n_intervals")],
    State("pt-enabled", "data"),
)
def refresh_paper(_, __, pt_enabled):
    # Check open trades
    try:
        pt_mod.refresh_open_trades()
    except Exception:
        pass

    summary = pt_mod.paper_trade_summary()
    wr_c = GREEN if (summary.get("win_rate") or 0) >= 50 else RED

    mode_badge = _pill(
        "PAPER ON" if pt_enabled else "PAPER OFF",
        GREEN if pt_enabled else DIM,
        "#0d2b1a" if pt_enabled else PANEL,
        "12px",
    )

    summary_row = [
        _stat_card("Open",         str(summary.get("open", 0))),
        _stat_card("Closed",       str(summary.get("closed", 0))),
        _stat_card("Win Rate",     f"{summary.get('win_rate') or '—'}%",   wr_c),
        _stat_card("Net R",        str(summary.get("net_r") or "—"),
                    GREEN if (summary.get("net_r") or 0) > 0 else DIM),
        _stat_card("Profit Factor",str(summary.get("profit_factor") or "—")),
    ]

    open_trades   = pt_mod.get_open_paper_trades()
    closed_trades = pt_mod.get_closed_paper_trades(limit=50)

    open_cols   = ["timestamp", "timeframe", "direction", "grade",
                    "entry", "stop_price", "target", "max_favorable", "max_adverse"]
    closed_cols = ["timestamp", "timeframe", "direction", "grade",
                    "entry", "stop_price", "target", "outcome", "pnl_pts", "pnl_r"]

    return (summary_row, mode_badge,
            _trade_rows_table(open_trades,   open_cols),
            _trade_rows_table(closed_trades, closed_cols))


@app.callback(
    Output("pt-report-container", "children"),
    Output("pt-report-container", "style"),
    Input("pt-report-btn", "n_clicks"),
    prevent_initial_call=True,
)
def show_weekly_report(_):
    import analytics as ana_mod2
    report_text = ana_mod2.weekly_report(paper_only=True)
    style = {
        "backgroundColor": PANEL, "border": f"1px solid {BORDER}",
        "borderRadius": "8px", "padding": "16px", "display": "block",
        "marginTop": "16px",
    }
    content = html.Pre(report_text, style={"color": TEXT, "fontSize": "12px",
                                            "lineHeight": "1.8", "margin": 0,
                                            "whiteSpace": "pre-wrap"})
    return content, style


# ── Profitability Report callback ─────────────────────────────────────────────

def _exp_table(rows: list[dict], key: str):
    if not rows:
        return html.Span("No data yet.", style={"color": DIM, "fontSize": "12px"})
    return dash_table.DataTable(
        data=rows,
        columns=[{"name": c.replace("_", " ").upper(), "id": c}
                 for c in [key, "trades", "win_rate", "avg_win_r", "avg_loss_r", "expectancy"]],
        style_table={"overflowX": "auto"},
        style_header={"backgroundColor": BORDER, "color": DIM,
                       "fontWeight": "600", "fontSize": "10px",
                       "border": f"1px solid {BORDER}"},
        style_cell={"backgroundColor": PANEL, "color": TEXT, "fontSize": "11px",
                    "border": f"1px solid {BORDER}", "padding": "4px 8px"},
        style_data_conditional=[
            {"if": {"filter_query": "{expectancy} > 0"},  "color": GREEN},
            {"if": {"filter_query": "{expectancy} < 0"},  "color": RED},
            {"if": {"filter_query": "{expectancy} = 0"},  "color": DIM},
        ],
        sort_action="native", page_size=8,
    )


@app.callback(
    [Output("prf-summary-row",   "children"),
     Output("prf-best-sess",     "children"),
     Output("prf-worst-sess",    "children"),
     Output("prf-best-setup",    "children"),
     Output("prf-worst-setup",   "children"),
     Output("prf-exp-sess",      "children"),
     Output("prf-exp-tf",        "children"),
     Output("prf-exp-grade",     "children"),
     Output("prf-exp-stype",     "children"),
     Output("prf-recommendations","children")],
    [Input("prf-refresh-btn", "n_clicks"),
     Input("prf-mode",        "value")],
    prevent_initial_call=False,
)
def refresh_profit(_, mode):
    paper_arg = None
    if mode == "paper":
        paper_arg = True
    elif mode == "live":
        paper_arg = False

    trades = db_mod.get_completed_trades(paper_only=(paper_arg or False))
    if mode == "live":
        trades = [t for t in trades if not t.get("paper_trade")]
    elif mode == "paper":
        trades = [t for t in trades if t.get("paper_trade")]

    stats = ana_mod.overall_stats(trades)

    no_data = html.Span("No completed trades yet.",
                        style={"color": DIM, "fontSize": "13px"})

    if not trades or not stats:
        empty = [no_data]
        return empty, no_data, no_data, no_data, no_data, no_data, no_data, no_data, no_data, no_data

    # ── KPI cards ─────────────────────────────────────────────────────────────
    wr_c  = GREEN if stats.get("win_rate", 0) >= 50 else RED
    exp   = stats.get("expectancy")
    exp_c = GREEN if exp and exp > 0 else (RED if exp and exp < 0 else DIM)
    pf    = stats.get("profit_factor")
    pf_c  = GREEN if pf and pf >= 1 else RED
    dd    = stats.get("max_drawdown_r", 0)

    summary_row = [
        _stat_card("Win Rate",       f"{stats.get('win_rate',0)}%",           wr_c),
        _stat_card("Profit Factor",  str(pf) if pf else "—",                  pf_c),
        _stat_card("Expectancy",     f"{exp:.3f}R" if exp is not None else "—", exp_c),
        _stat_card("Avg R / Trade",  f"{stats.get('avg_r_per_trade',0):.2f}R", GOLD),
        _stat_card("Max Drawdown",   f"{dd:.2f}R",                             RED),
        _stat_card("Net R",          f"{stats.get('net_r',0):.2f}R",
                    GREEN if (stats.get("net_r") or 0) > 0 else RED),
        _stat_card("Total Trades",   str(stats.get("total", 0))),
    ]

    # ── Session breakdown ─────────────────────────────────────────────────────
    sess_rows  = ana_mod.win_rate_table("session", trades)

    def _mini_table(rows, key, sort_desc=True):
        if not rows:
            return html.Span("Not enough data.", style={"color": DIM, "fontSize": "12px"})
        display = sorted(rows, key=lambda r: r["win_rate"], reverse=sort_desc)[:5]
        return dash_table.DataTable(
            data=display,
            columns=[{"name": c.replace("_"," ").upper(), "id": c}
                     for c in [key, "trades", "win_rate", "avg_rr"]],
            style_table={"overflowX": "auto"},
            style_header={"backgroundColor": BORDER, "color": DIM,
                           "fontWeight": "600", "fontSize": "10px",
                           "border": f"1px solid {BORDER}"},
            style_cell={"backgroundColor": PANEL, "color": TEXT, "fontSize": "11px",
                        "border": f"1px solid {BORDER}", "padding": "4px 8px",
                        "maxWidth": "240px", "overflow": "hidden",
                        "textOverflow": "ellipsis"},
            style_data_conditional=[
                {"if": {"filter_query": "{win_rate} >= 55"}, "color": GREEN},
                {"if": {"filter_query": "{win_rate} < 45"},  "color": RED},
            ],
            page_size=5,
        )

    best_sess  = _mini_table(sess_rows, "session", sort_desc=True)
    worst_sess = _mini_table(sess_rows, "session", sort_desc=False)

    # ── Setup breakdown (TF|session|signal_type) ──────────────────────────────
    best_setup_rows  = ana_mod.best_setups(trades,  top_n=5)
    worst_setup_rows = ana_mod.worst_setups(trades, top_n=5)

    def _setup_mini(rows, key_color):
        if not rows:
            return html.Span("Not enough data.", style={"color": DIM, "fontSize": "12px"})
        return dash_table.DataTable(
            data=rows,
            columns=[{"name": c.upper(), "id": c}
                     for c in ["setup", "trades", "win_rate", "avg_r"]],
            style_table={"overflowX": "auto"},
            style_header={"backgroundColor": BORDER, "color": DIM,
                           "fontWeight": "600", "fontSize": "10px",
                           "border": f"1px solid {BORDER}"},
            style_cell={"backgroundColor": PANEL, "color": TEXT, "fontSize": "11px",
                        "border": f"1px solid {BORDER}", "padding": "4px 8px",
                        "maxWidth": "300px", "overflow": "hidden",
                        "textOverflow": "ellipsis"},
            style_data_conditional=[{"if": {"column_id": "win_rate"}, "color": key_color}],
            page_size=5,
        )

    best_setup  = _setup_mini(best_setup_rows,  GREEN)
    worst_setup = _setup_mini(worst_setup_rows, RED)

    # ── Expectancy tables ─────────────────────────────────────────────────────
    exp_sess  = _exp_table(ana_mod.expectancy_by("session",     trades), "session")
    exp_tf    = _exp_table(ana_mod.expectancy_by("timeframe",   trades), "timeframe")
    exp_grade = _exp_table(ana_mod.expectancy_by("grade",       trades), "grade")
    exp_stype = _exp_table(ana_mod.expectancy_by("signal_type", trades), "signal_type")

    # ── Recommendations ───────────────────────────────────────────────────────
    recs = []
    if sess_rows:
        worst_s = min(sess_rows, key=lambda r: r["win_rate"])
        best_s  = max(sess_rows, key=lambda r: r["win_rate"])
        if worst_s["win_rate"] < 40:
            recs.append(f"Avoid {worst_s['session']} — only {worst_s['win_rate']}% win rate "
                        f"({worst_s['trades']} trades). Consider filtering it out entirely.")
        if best_s["win_rate"] >= 60:
            recs.append(f"Focus on {best_s['session']} — strongest session at "
                        f"{best_s['win_rate']}% win rate.")

    exp_by_grade = ana_mod.expectancy_by("grade", trades)
    for row in exp_by_grade:
        if row.get("expectancy", 0) < 0:
            recs.append(f"Grade {row['grade']} has NEGATIVE expectancy ({row['expectancy']:.3f}R) "
                        f"— raise the minimum confluence score or disable this grade.")
        elif row.get("expectancy", 0) > 0.3:
            recs.append(f"Grade {row['grade']} is your best edge ({row['expectancy']:.3f}R expectancy) "
                        f"— increase size allocation here.")

    if stats.get("avg_mae_pts", 0) > stats.get("avg_mfe_pts", 0):
        recs.append("Avg MAE > Avg MFE — stops may be too tight or entries are chasing. "
                    "Consider wider stops or waiting for deeper pullbacks.")

    if (stats.get("profit_factor") or 0) < 1.0 and stats.get("total", 0) >= 10:
        recs.append("Profit factor < 1.0 — losing more than winning in dollar terms. "
                    "Focus on higher R:R setups (minimum 2.5R) and cut B-grade trades.")

    if not recs:
        recs.append("Accumulate more completed trades for statistically meaningful recommendations.")

    rec_el = html.Div([
        html.Div(f"→  {r}", style={
            "color": GOLD, "fontSize": "12px", "lineHeight": "2.0",
            "borderBottom": f"1px solid {BORDER}", "padding": "4px 0",
        }) for r in recs
    ], style={"backgroundColor": PANEL, "border": f"1px solid {BORDER}",
               "borderRadius": "8px", "padding": "12px 16px"})

    return (summary_row, best_sess, worst_sess, best_setup, worst_setup,
            exp_sess, exp_tf, exp_grade, exp_stype, rec_el)


# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("NQB  →  http://127.0.0.1:8050")
    app.run(debug=False, host="127.0.0.1", port=8050)
